// Code generated by "stringer -type Mode"; DO NOT EDIT.

package frontmatter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SetMetadata-1]
}

const _Mode_name = "SetMetadata"

var _Mode_index = [...]uint8{0, 11}

func (i Mode) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Mode_index)-1 {
		return "Mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mode_name[_Mode_index[idx]:_Mode_index[idx+1]]
}
